-- 할인 가능 대여 기간 : 7, 30, 90
-- 차종 : 세단, SUV
-- 기간 : 2022-11-01 ~ 2022-11-30, 총 30일
-- 대여 금액 : 50 이상 ~ 200 미만
-- 출력 : CAR_ID, CAR_TYPE, DAILY_FEE (FEE)
-- 정렬 : FEE DESC, CAR_TYPE, CAR_ID DESC

SELECT C.CAR_ID, C.CAR_TYPE, 
        ROUND((C.DAILY_FEE * (100 - DISCOUNT_RATE) / 100 * 30), 0) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR C
        JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
            ON C.CAR_ID = H.CAR_ID
        JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
            ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-12-01')
    AND DURATION_TYPE LIKE '30%'
    AND C.CAR_TYPE IN ('세단', 'SUV')
    AND ROUND((C.DAILY_FEE * (100 - DISCOUNT_RATE) / 100 * 30), 0)
        BETWEEN 500000 AND 2000000
GROUP BY C.CAR_ID
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;
    