# FIRST_HALF (FLAVOR) 상반기 주문 정보
# JULY (SHIPMENT_ID)  7월 주문 정보
# --> FLAVOR (FK)

SELECT FH.FLAVOR
FROM FIRST_HALF FH JOIN JULY J
    ON FH.FLAVOR = J.FLAVOR
GROUP BY FLAVOR
ORDER BY SUM(FH.TOTAL_ORDER + J.TOTAL_ORDER) DESC
LIMIT 3;